### ISSUE TITLE
Reading BIGNUMERIC(38) throws incorrect java.lang.ArithmeticException: Decimal precision 46 exceeds max precision 38 exception on the newest connector

### ISSUE THREAD

**Issue by cheare** [GoogleCloudDataproc/spark-bigquery-connector#1026]
We work with an externally created BQ table (it's a result of a GCP replication service - Datastream, and the datatypes are defined by this service - beyond our control). 

The table contains (among others) a column CTX_ID with a datatype „BIGNUMERIC(38)”.
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/6576102a-7e14-4814-a14b-7c03239be5a8)

Note, that max length of the number in this column is 9:
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/b7ad34b1-9433-4005-9c27-0cf9f4a56865)

And also all queries in BQ runs with no problem on this column:
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/ef4294ba-7098-4b24-adb5-8a4ad4a56c2c)

However using spark and the newest BQ connector simple show() on the table with this column does not work:
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/2def71e1-4ee0-4be6-be44-10e58d4a56df)
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/8482ba86-d2a6-406e-bf01-06dd534e1b9a)
The problematic are the columns BIGNUMERIC(38). When running select excluding those columns, everything works fine:
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/cdd1c1ea-b282-4ca5-907a-00fbe8bc8b25)
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/37f09743-f861-425d-8a1c-851da5637b03)
VS ‘problematic’ column:
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/d74cd79a-b070-414c-b9d3-db12cc5c59ed)
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/d84e5fbd-c322-49f3-aef5-fb40eda54530)

This happens when the new version of connector is being used (default or explicit spark-bigquery-with-dependencies_2.13-0.32.0.jar):
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/7c86000e-7260-44fa-910d-0eb9010bb844)

with the older version (spark-bigquery-with-dependencies_2.13-0.30.0.jar) it does work:
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/51e5331e-c1e4-45b1-a902-dd011662e9ff)

![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/29750890/d57927bb-6267-4706-99d4-486b707c4cd8)

**Comment by rinek** [comment]
Additionaly when BIGNUMERIC(38) column contains only null values, problem doesn't occur (connector version 0.31.0+)
It seems like values are casted to string and casted back to numeric value, but with prepended 38 '0' chars.

len(bignumeric_column) == 9
string '00000000000000000000000000000000000000'+'123456789' has len of 47 and exceeds max precision for Spark
java.lang.ArithmeticException

len(bignumeric_column) == 6
string '00000000000000000000000000000000000000'+'123456' has len of 44 and exceeds max precision for Spark
throwing  java.lang.ArithmeticException

len(bignumeric_column) == 0
string '00000000000000000000000000000000000000'+'' has len of 38, and there is no problem.

**Comment by suryasoma** [comment]
In the latest release we have made updated to the Decimal types https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/955 which is to make all numeric reflect the same Precision and scale as the other system.

But, as part of that PR, if no scale is given to the BigNumeric type, we give the default scale which is 38 https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/741bdb33bf5c06fb3fad9defffa65ea1470d2690/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SchemaConverters.java#L359

So the problem is when we set the scale to be 38, and there is an existing issue on Spark side https://issues.apache.org/jira/browse/SPARK-20427, where Spark adds additional 0's equaling to scale value after dot(.). Therefore for your case since there are 9 digits the decimal becomes a value of 123456789.0000000000000000000000000000000000000 with a precision on 47(38+9).

As a workaround for now, as mentioned in the ticket https://issues.apache.org/jira/browse/SPARK-20427?focusedCommentId=17107376&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17107376, you can use custom schema while loading the data.

![Screenshot 2023-07-25 at 2 37 14 PM](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/12949447/6bd153fe-711a-4f36-8851-fe973d20266b)

**Comment by davidrabinowitz** [comment]
FYI PR #1033

**Comment by cheare** [comment]
Above fix (available in v0.32.1) solves the issue completely. Thank you!
