### ISSUE TITLE
Policy tags removed when using the latest version (0.32.0)

### ISSUE THREAD

**Issue by khaledh** [GoogleCloudDataproc/spark-bigquery-connector#1028]
We noticed that, after upgrading to the latest connector version 0.32.0, that policy tags on existing tables are gone when the table is overwritten. I looked at the changes between 0.31.1 and 0.32.0, and the only place I could find where this might be impacted is this the change from using `MERGE` sql to a different method for writing the table: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/1007/files#diff-e88b374462a4b02ea34682a5d84516528082df1fb08189222dc2053ff6a8bcbaR211-R241

**Comment by suryasoma** [comment]
Can you please provide the code for writing into the table.

**Comment by khaledh** [comment]
Sure:

```python
df.write \
    .format('bigquery') \
    .option('writeMethod', 'direct') \
    .mode('overwrite') \
    .save('myproject.mydataset.mytable')
```

**Comment by suryasoma** [comment]
Thanks for identifying the issue. Yes, https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/1007 introduced this issue as we updated the query from `MERGE` to `SELECT` along with `writeDeposition= WRITE_TRUNCATE`.

This is a know issue in the BigQuery API side when `WRITE_TRUNCATE` is used the policy tags are removed https://www.googlecloudcommunity.com/gc/Developer-Tools/Bug-in-Python-BigQuery-API-with-adding-policy-tags-to-a-table/td-p/181230 
We will update the ticket either once we find the fix for the issue.

Thanks.

**Comment by khaledh** [comment]
@suryasoma Thanks, much appreciated. I left a [comment](https://partnerissuetracker.corp.google.com/issues/187435090#comment6) on the issue tracker.

**Comment by khaledh** [comment]
Just curious, would it be possible to revert that part in the connector until a proper fix is available through the API? Right now this is a big issue that could leak PII (due to missing policy tags).

**Comment by khaledh** [comment]
@suryasoma We noticed that while this issue is resolved for direct writes, it still happens when we use indirect writes; the policy tags are dropped after the indirect write. I wonder if there's another code path that needs to be fixed?

**Comment by khaledh** [comment]
Follow up: we also noticed that non-nullable columns are created as nullable when using indirect write. We're trying to work around this issue, but we're hoping it would be fixed in the connector itself.

**Comment by davidrabinowitz** [comment]
Hi @khaledh , can you please open a new issue for that? Also, which intermediate format are you using?

**Comment by khaledh** [comment]
@davidrabinowitz Will do. We tried both parquet and avro.
