### ISSUE TITLE
JARs marked 'latest' not being updated

### ISSUE THREAD

**Issue by dmedora** [GoogleCloudDataproc/spark-bigquery-connector#1202]
The Cloud Storage bucket with the connector jars contains four jars named 'latest':

- gs://spark-lib/bigquery/spark-2.4-bigquery-latest.jar
- gs://spark-lib/bigquery/spark-bigquery-latest.jar
- gs://spark-lib/bigquery/spark-bigquery-latest_2.11.jar
- gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar

However, they all appear to be from April 2023. This is leading to some confusion for customers. It would be great if they are either kept up-to-date with the latest release or removed. Thanks!

**Comment by davidrabinowitz** [comment]
Please do not use the `-latest` jars. It is better to configure your application to use a specific version of the connector, instead of having a dependency changing in practice without you know about it.
Also, the `-latest` jars are only of the old flavor of the connector (`spark-bigquery-with-dependencies_2.12.jar`), it is recommended to use the latest flavor of the connector (`spark-X.Y-bigquery.jar`)
