### ISSUE TITLE
spark.read.bigquery("publicdata:samples.shakespeare") causes DataFrameReader error

### ISSUE THREAD

**Issue by tfayyaz** [GoogleCloudDataproc/spark-bigquery-connector#141]
I tried to run the following example from the main readme page in PySpark

```python
spark.read.bigquery("publicdata:samples.shakespeare") \
  .select("word") \
  .where("word = 'Hamlet' or word = 'Claudius'") \
  .collect()
```

and receive the following error

```shell
AttributeError                            Traceback (most recent call last)
<ipython-input-35-6f8b98eea8e9> in <module>
----> 1 spark.read.bigquery("publicdata:samples.shakespeare") \
      2   .select("word") \
      3   .where("word = 'Hamlet' or word = 'Claudius'") \
      4   .collect()

AttributeError: 'DataFrameReader' object has no attribute 'bigquery'
```

Is it valid using spark.read.bigquery or is that a deprecated method?

**Comment by davidrabinowitz** [comment]
`spark.read.bigquery()` does not work in PySpark, only in Scala. In order to have it working in Scala you need to add the following import: `import com.google.cloud.spark.bigquery._`

For all languages, you can use 
```
df = spark.read.format("bigquery").option("table","publicdata:samples.shakespeare").load()
```

You can check [this python example](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/examples/python/shakespeare.py).
