### ISSUE TITLE
Writing out Array types from Spark introduces 'list' nested field

### ISSUE THREAD

**Issue by tanjinP** [GoogleCloudDataproc/spark-bigquery-connector#251]
I have a schema in Spark that looks like the following (`df.printSchema()`)
```
root
 |-- diagnoses: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- surrogate: struct (nullable = false)
 |    |    |    |-- id: string (nullable = false)
 |    |    |    |-- project: string (nullable = false)
 |    |    |    |-- dataset: string (nullable = false)
 |    |    |    |-- table: string (nullable = false)
 |    |    |-- tier: string (nullable = false)
 |    |    |-- codeset: string (nullable = false)
 |    |    |-- code: string (nullable = false)
```

When I write this to BigQuery (`df.write.format('bigquery').mode('overwrite').option('table',BQ_TABLE_LOCATION).save()`), this is what the schema looks like on BigQuery:
![Screen Shot 2020-10-06 at 12 39 12 PM](https://user-images.githubusercontent.com/9021117/95231416-21b4fa00-07d1-11eb-8761-77c1239af0f5.png)

Why is there a `list` column/name? How can I ensure it does not get included in the table that is written out? I was not expecting it.

**Comment by davidrabinowitz** [comment]
It is a known issue when using parquet as the intermediate format. Please use ORC or Avro instead. Please notice that for Avro you would need to add the spark-avro package.

**Comment by glthu** [comment]
I run into below issue after change to use "orc" . I've tried on a 10 cols table with a array of struct type col and succeed while our BQ Table have almost 1800 cols. I think it's still having issue when handling tables with thousands of cols.

Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: Data cannot be parsed within the memory limit. Try reducing the data size or not using compression. at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:411)
