### ISSUE TITLE
Project option is not picked up when query option is used

### ISSUE THREAD

**Issue by mariosmeim-db** [GoogleCloudDataproc/spark-bigquery-connector#342]
If the project where the dataset/table to execute the query on is not defined in the query, the connector will try to resolve the dataset/table in the `parentProject` parameter (implicitly or explicitly). 

For example, this command is successful:

    val query = "select * from `some-project.some-dataset.some-table`"

    val df = spark.read.format("bigquery")
    .option("query", query)
    .option("parentProject", "<some-parent-project>")
    .option("materializationDataset", "<some_dataset>")
    .load()

while this command will try to find `some-dataset` inside `some-parent-project`, efffectively skipping the `project` parameter:

    val query = "select * from `some-dataset.some-table`"

    val df = spark.read.format("bigquery")
    .option("query", query)
    .option("project", "<some-project>")
    .option("parentProject", "<some-parent-project>")
    .option("materializationDataset", "<some_dataset>")
    .load()

Is this by design? Should the project be part of the query when the `query` option is used?

**Comment by davidrabinowitz** [comment]
I'll check this, thanks

**Comment by alexoss68** [comment]
@davidrabinowitz  Have you had a chance to check it?

**Comment by himanshukohli09** [comment]
Hi Marios,

Yes, this is by design. The option "parentProject" is used for billing project (and can be used to specify the default project). The option "project" is used while reading data from a table via the load() method.  Now, in case we use option "query" and the source dataset/table are not present in the "parentProject" then use the fully qualified table name : {project}.{dataset}.{table_name}.
