### ISSUE TITLE
Temporary Table didn't get dropped while Reading BQ table

### ISSUE THREAD

**Issue by arunkindra** [GoogleCloudDataproc/spark-bigquery-connector#529]
Hello,

While reading data from a BigQuery query using below code, it create a temporary table in materializationDataset which didn't get dropped once the job get completed. This is creating lot of unnecessary tables under our production dataset.

spark.conf.set("viewsEnabled","true")
spark.conf.set("materializationDataset","<dataset>")

sql = """
  SELECT tag, COUNT(*) c
  FROM (
    SELECT SPLIT(tags, '|') tags
    FROM `bigquery-public-data.stackoverflow.posts_questions` a
    WHERE EXTRACT(YEAR FROM creation_date)>=2014
  ), UNNEST(tags) tag
  GROUP BY 1
  ORDER BY 2 DESC
  LIMIT 10
  """
df = spark.read.format("bigquery").load(sql)
df.show()

**Comment by davidrabinowitz** [comment]
Those tables are needed as the query result must be materialized in order for the connector to read it.  By default those table are expired after 24 hours, but you can control this time using the `materializationExpirationTimeInMinutes` option. 

In addition, you can create a `temp` dataset in order to hold those temporary tables (similar to the `/tmp` directory), reducing the clutter from the production dataset. The dataset can be configured by the `materializationDataset ` option.

**Comment by MattConflitti** [comment]
@davidrabinowitz I have come into the same issue. I have two processes that read from an external location (delta table format). One process uses spark.sql() and the other used spark.read(). Spark.sql creates temp tables with no expiration while spark.read() defaults to a 24 expiry time. Is this expected behavior?
