### ISSUE TITLE
How to guarantee exactly-once in direct write API?

### ISSUE THREAD

**Issue by jiayue-zhang** [GoogleCloudDataproc/spark-bigquery-connector#533]
When using the direct write API to write to BQ, is it using the committed mode found in this Google [document](https://cloud.google.com/bigquery/docs/write-api#committed)? (I assume this is the [class](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDirectDataSourceWriterContext.java) that handles direct write API.) And how to guarantee exactly-once delivery using the spark-bigquery-connector?

**Comment by VinayLondhe14** [comment]
@jiayue-zhang Thank you for the questions. 

In the direct API write to BQ, the connector is using the Pending mode and not the Committed mode. The code for the same is [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDirectDataWriterHelper.java#L96). 

In a particular write session, we do guarantee exactly-once delivery since we use offsets. If there is a mismatch in the offsets, an exception is thrown and the write is not committed.

**Comment by Deepi21** [comment]
Does indirect-write https://github.com/GoogleCloudDataproc/spark-bigquery-connector#indirect-write also guarantee exactly-once semantics ?

**Comment by VinayLondhe14** [comment]
The indirect-write does not guarantee exactly-once semantics.
