### ISSUE TITLE
pushAllFilters doesn't seem to work

### ISSUE THREAD

**Issue by GodefroyClair** [GoogleCloudDataproc/spark-bigquery-connector#552]
Using:
- bigquery-connector-version=1.2.0 
- spark-bigquery-connector-version=0.23.0

When I call the following code :
```
from pyspark.sql import SparkSession

spark = SparkSession \
  .builder \
  .master('yarn') \
  .appName('spark-bigquery-read-test') \
  .getOrCreate()

df = spark.read \
  .format("bigquery") \
  .option("table", "bigquery-public-data.samples.natality")\
  .option("pushAllFilters", False)\
  .load()\
  .filter("state = 'CA'")\
  .select("source_year", "is_male", "state")
df.explain("extended")
```

I get the following output:
```
== Physical Plan ==
*(1) Scan BigQueryRelation(bigquery-public-data.samples.natality
numRows=137,826,763
numBytes=23,562,717,384
) [source_year#200L,is_male#206,state#205] PushedFilters: [*IsNotNull(state), *EqualTo(state,CA)], ReadSchema: struct<source_year:bigint,is_male:boolean,state:string>
```

So even though I set `pushAllFilters` to `False`the filter on state is still pushed down "PushedFilters: [*IsNotNull(state), *EqualTo(state,CA)]"

Am I missing something?

**Comment by suryasoma** [comment]
Hi @GodefroyClair, we just want to understand the usecase here. Since the behavior currently is if pushAllFilters option is set to False, it will not push all the filters, instead only push those which are supported in BigQuery. 
It is a safety flag which helps in creating a session by not pushing invalid Filters.
