### ISSUE TITLE
Better documentation about what gets pushed down to BigQuery

### ISSUE THREAD

**Issue by mkleinbort** [GoogleCloudDataproc/spark-bigquery-connector#87]
Hello, 

I'm working through a project using this connector, and I can't find what does and does not get pushed down to BigQuery.

E.g. Where clauses? GroupBy? Distinct? Joins?

**Comment by davidrabinowitz** [comment]
In order to parallelize the read and increase its performance, we use the [BigQuery Storage API](https://cloud.google.com/bigquery/docs/reference/storage/), which reads directly from the data files BigQuery itself uses. This method is much suitable for bulk reads, but it has its limitations - there is no query engine underneath. Therefore group by, distinct and join or any reference to other tables cannot be pushed down. Where filters are pushed down.

[The BigQuery Client](https://cloud.google.com/bigquery/docs/reference/libraries) is more flexible, as it can run any query on BigQuery. However the result is returned in a single thread.

There is a way to enjoy both worlds at the moment, using views. Run a "create view" query using a standard BigQuery client, and then read this view directly into a dataframe using the connector as you would read any other table.

**Comment by mkleinbort** [comment]
Thank you, sounds great (and explains why it was not registering as BigQuery usage)!

To clarify how where/select clauses get pushed down. If I were to write:

```
s = (spark
    .read
    .format('bigquery')
    .option('project', 'my-project-analytics')
    .option('table', 'transactions.all_transactions_ever')
    .load()
)

s = (s.
    .where(f.col('date').between('2010-01-01', '2011-01-01'))
    .where(f.col('voided') != True)
    .where(f.col('sales_amount') > 0)
    .select('date', 'item_id', 'sales_amount')
)
```

would all the where/select clauses be pushed down? 

Or are there conditions on BigQuery enforcing partitions/grouped data?

**Comment by davidrabinowitz** [comment]
Version 0.12.0-beta adds logging for the columns and the filters it receives from the spark DataSource API, and which it pushes down to BigQuery
